services:
  web:
    image: ocsinventory/ocsinventory-docker-image:2.10
    container_name: ocsinventory-server
    environment:
      - OCS_DB_SERVER=ocsinventory-db
      - OCS_MYSQL_USER=ocs
      - OCS_MYSQL_PASS=ocs
      - OCS_MYSQL_DBNAME=ocsweb
    volumes:
      - ocsdownload:/usr/share/ocsinventory-reports/ocsreports/download/
      - ocssrv:/etc/ocsinventory-reports/
      - ocslib:/var/lib/ocsinventory-reports/
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:8.0
    container_name: ocsinventory-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mdp
      - MYSQL_USER=ocs
      - MYSQL_PASSWORD=ocs
      - MYSQL_DATABASE=ocsweb
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
  ocsdownload:
    driver: local
  ocslib:
    driver: local
